POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkaWw2NTkiLCJpZCI6IjVmNmI1NmI2OTA2Yzk5NjJkODgzOGIxMCIsImlhdCI6MTYwMDg3NDE1Nn0.azj_keePPf3bqExyGhhvcapfwCOqU1BjCumoC8n6h9E

{
    "title": "React patterns", 
    "author": "Michael Chan", 
    "url": "https://reactpatterns.com/", 
    "likes": 7
}